#!/usr/bin/env sh

# Runs all directories setup script

cd "$(dirname "$0")"

DIRS=$(ls -d $PWD/*/)

for DIR in $DIRS; do
  echo
  echo "[$(basename $DIR)]"

  if test -x $DIR/_setup; then
    $DIR/_setup
  else
    echo "No _setup found, nothing to do."
  fi

  if test -x $DIR/_setup.root; then
    echo "See _setup.root script for system specific configuration."
  fi
done
