#!/usr/bin/env sh

# Runs all directories setup script

DIRS=$(ls -d $PWD/*/)

for DIR in $DIRS; do
  echo
  echo "[$(basename $DIR)]"
  if test -x $DIR/_setup; then
    cd $DIR
    ./_setup
  else
    echo "No setup instruction found."
  fi
done
