"" Standard options
:set number
:syntax on

"" Remapping (for colemak layout)
:nnoremap j k  
:nnoremap k j
:imap hh <Esc>
:nmap ; :
:nnoremap ; :
:nnoremap : ;
:vnoremap ; :
:vnoremap : ;

"" Filetype settings
au BufRead,BufNewFile *.md set filetype=markdown

"" GUI specific options
:set guioptions-=m "remove menu bar
:set guioptions-=T "remove toolbar
:set guioptions-=r "remove right-hand scroll bar
:set guioptions-=L "remove left-hand scroll bar
