# Zstyles

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# History

HISTSIZE=2000
SAVEHIST=2000
HISTFILE=~/.zsh_history

# Dirstack

DIRSTACKSIZE=20

if [[ -f $DIRSTACKFILE ]] && [[ $#dirstack -eq 0 ]]; then
  dirstack=(${(f)"$(< $DIRSTACKFILE)"})
  [[ -d $dirstack[1] ]] && cd $dirstack[1]
fi

setopt autopushd pushdsilent pushdtohome
setopt pushdignoredups
setopt pushdminus

# Includes

source ~/.zsh.d/aliases
source ~/.zsh.d/inputs
source ~/.zsh.d/prompt