(setq ido-enable-flex-matching t)
(setq ido-everywhere t)
(ido-mode 1)
(load-theme 'misterioso)
(menu-bar-mode -1)
(toggle-scroll-bar -1)
(tool-bar-mode -1)
(add-to-list 'default-frame-alist '(font . "Ubuntu Mono 14"))
;;(add-to-list 'default-frame-alist '(height . 40))
;;(add-to-list 'default-frame-alist '(width . 80))
(setq-default indicate-empty-lines t)
(setq inhibit-splash-screen t)
(setq inhibit-startup-screen t)
(setq tab-width 2)
(setq ring-bell-function (lambda () nil))
(setq auto-save-default nil)
(setq make-backup-files nil)
(setq backup-by-copying nil)
(add-hook 'write-file-function 'delete-trailing-whitespace)
(fset 'yes-or-no-p 'y-or-n-p)
(setq-default indent-tabs-mode nil)
(setq-default tab-width 2)
(setq-default message-log-max nil)
(delete-selection-mode t)
(show-paren-mode t)
(setq shift-select-mode nil)
(setq select-enable-clipboard t)
(setq interprogram-paste-function 'x-cut-buffer-or-selection-value)
(setq-default truncate-lines t)
(setq mouse-wheel-follow-mouse (quote t))
(setq mouse-wheel-mode t)
(setq mouse-wheel-progressive-speed nil)
(setq mouse-wheel-scroll-amount (quote (3 ((shift) . 1))))
(if (>= emacs-major-version 26)
    (add-hook 'prog-mode-hook #'display-line-numbers-mode)
  (add-hook 'prog-mode-hook #'linum-mode))
(global-auto-revert-mode)
(global-set-key (kbd "C-h") (kbd "<backspace>"))
(global-set-key (kbd "C-S-h") (kbd "C-<backspace>"))
(global-set-key (kbd "C-x C-k") 'kill-this-buffer)
(global-set-key (kbd "C-h") 'backward-delete-char-untabify) ; remaping is better
(global-set-key (kbd "C-;") 'comment-dwim)
(global-set-key (kbd "C-S-l") 'visual-line-mode)
(global-set-key (kbd "C-<") 'beginning-of-buffer)
(global-set-key (kbd "C->") 'end-of-buffer)
(define-prefix-command 'leader-key-map)
(global-set-key (kbd "C-t") 'leader-key-map)
(define-key leader-key-map (kbd "<SPC>") 'execute-extended-command)
(define-key leader-key-map (kbd "r") 'rectangle-mark-mode)
(global-set-key (kbd "C-+") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
;; (global-set-key [remap kill-region] 'kill-ring-save)
;; (global-set-key [remap kill-ring-save] 'kill-region)
