# Make this Emacs config yours

# Variables

TOOL        = Emacs
THIS_CONFIG = $(shell pwd)/emacs
YOUR_CONFIG = $(HOME)/.emacs

# Actions

all: set

set:
	@ echo "<$(TOOL)>"
	@ ln -i -s $(THIS_CONFIG) $(YOUR_CONFIG)

