# Includes

if [ -f $HOME/.config/bash/includes/local.sh ]; then
  source $HOME/.config/bash/includes/local.sh
fi

source $HOME/.config/bash/includes/exports.sh
source $HOME/.config/bash/includes/aliases.sh
source $HOME/.config/bash/includes/prompt.sh
source $HOME/.config/bash/includes/plugins.sh
source $HOME/.config/bash/includes/terminal-options.sh
